# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Data Expressions
author: Jung Hoon Son, M.D.
copyright: "2023"
logo: data_expressions_logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false

# Spinx options
# These are very specific to Sphinx, pydata_sphinx_theme
# https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/install.html
# sphinx:
#     config:
#         html_theme: "pydata_sphinx_theme"